### ISSUE TITLE
suggestion: move index-gathering to brainio_collection/fetch instead of constructor

### ISSUE THREAD

**Issue by mschrimpf** [brain-score/brainio_base#4]
Automatically gathering all indices in the constructor can be confusing as it e.g. squashes single-coordinate dimensions (https://github.com/pydata/xarray/issues/2537).
Instead, we could set the indices in the code responsible for de-/serializing, i.e. brainio_collection's fetch.py https://github.com/brain-score/brainio_collection/blob/f2452ec362eb413c942fd8870ccaa34a9c25d3b7/brainio_collection/fetch.py#L130

**Comment by jjpr-mit** [comment]
Brain-Score makes use of the MultiIndex guarantee of the __init__, so this is not advisable.
